# Generated by Django 4.1.1 on 2022-09-13 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 18, 23, 6, 908129)),
        ),
    ]
