# Generated by Django 4.1.1 on 2022-09-12 18:10

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_course_user_alter_course_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coeducational',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 9, 12, 22, 40, 20, 424818)),
        ),
    ]
