# Generated by Django 4.1.1 on 2022-09-12 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0007_alter_course_coeducational_alter_course_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 9, 12, 23, 14, 5, 504113)),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
