# Generated by Django 4.1.1 on 2022-09-12 18:54

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_alter_course_exam_alter_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='from_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='to_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='exam',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2022, 9, 12, 23, 24, 22, 61922)),
        ),
    ]
