# Generated by Django 4.1.1 on 2022-09-13 13:53

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_alter_classtime_from_hour_alter_classtime_to_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exam',
        ),
        migrations.AddField(
            model_name='course',
            name='exam_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 9, 13)),
        ),
        migrations.AddField(
            model_name='course',
            name='exam_hour',
            field=models.TimeField(null=True),
        ),
    ]
